CREATE TABLE IF NOT EXISTS public."ACCOUNTS"
(
  "ACCOUNT_ID" serial NOT NULL UNIQUE,
  "USERNAME" character varying(50) NOT NULL,
  "PASSWORD" character varying(100) NOT NULL,
  CONSTRAINT "ACCOUNTS_pkey" PRIMARY KEY ("ACCOUNT_ID")
);

-- CREATE TABLE IF NOT EXISTS public."SCORES"
-- (
--   "SCORE_ID" serial NOT NULL UNIQUE,
--   "ACCOUNT_ID" bigint NOT NULL,
--   "SCORE" numeric NOT NULL,
--   "HIGHEST_STREAK" smallint NOT NULL,
--   "DATE" date NOT NULL,
--   CONSTRAINT "SCORES_pkey" PRIMARY KEY ("SCORE_ID"),
--   CONSTRAINT "SCORE_ACCOUNT" FOREIGN KEY ("ACCOUNT_ID")
--       REFERENCES public."ACCOUNTS" ("ACCOUNT_ID") MATCH SIMPLE
--       ON DELETE NO ACTION ON UPDATE NO ACTION
-- );

CREATE TABLE IF NOT EXISTS public."QUESTIONS"
(
  "QUESTION_ID" serial NOT NULL UNIQUE,
  "QUESTION_CONTENT" character varying(1000),
  "RIGHT_ANSWER" character varying(1000),
  "WRONG_ANSWER1" character varying(1000),
  "WRONG_ANSWER2" character varying(1000),
  "WRONG_ANSWER3" character varying(1000),
  "ACCOUNT_ID" bigint NOT NULL,
  CONSTRAINT "QUESTIONS_pkey" PRIMARY KEY ("QUESTION_ID"),
  CONSTRAINT "FK_ACCOUNT_QUESTION" FOREIGN KEY ("ACCOUNT_ID")
      REFERENCES public."ACCOUNTS" ("ACCOUNT_ID") MATCH SIMPLE
      ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE public."QUIZ_DIFFICULTY"
(
    "DIFFICULTY_ID" integer NOT NULL DEFAULT nextval('"QUIZ_DIFFICULTY_DIFFICULTY_ID_seq"'::regclass),
    "DIFFICULTY_LEVEL" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "QUIZ_DIFFICULTY_pkey" PRIMARY KEY ("DIFFICULTY_ID")
);

CREATE TABLE public."QUIZ_CATEGORY"
(
    "QUIZ_CATEGORY_ID" integer NOT NULL DEFAULT nextval('"QUIZ_CATEGORY_QUIZ_CATEGORY_ID_seq"'::regclass),
    "CATEGORY_NAME" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "QUIZ_CATEGORY_pkey" PRIMARY KEY ("QUIZ_CATEGORY_ID")
);

CREATE TABLE public."SCORES"
(
    "SCORE_ID" bigint NOT NULL DEFAULT nextval('"SCORES_SCORE_ID_seq"'::regclass),
    "ACCOUNT_ID" bigint NOT NULL,
    "SCORE" double precision NOT NULL,
    "HIGHEST_STREAK" smallint NOT NULL,
    "DATE" timestamp(6) without time zone NOT NULL,
    "QUIZ_CATEGORY_ID" integer NOT NULL DEFAULT 0,
    "DIFFICULTY_ID" integer NOT NULL DEFAULT 0,
    CONSTRAINT "SCORES_pkey" PRIMARY KEY ("SCORE_ID"),
    CONSTRAINT "DIFFICULTY_ID" FOREIGN KEY ("DIFFICULTY_ID")
        REFERENCES public."QUIZ_DIFFICULTY" ("DIFFICULTY_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "QUIZ_CATEGORY_ID" FOREIGN KEY ("QUIZ_CATEGORY_ID")
        REFERENCES public."QUIZ_CATEGORY" ("QUIZ_CATEGORY_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "SCORE_ACCOUNT" FOREIGN KEY ("ACCOUNT_ID")
        REFERENCES public."ACCOUNTS" ("ACCOUNT_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);